version: 2

jobs:
  linux:
    docker:
      - image: swift:5.1
    steps:
      - checkout
      - run:
          name: Update package
          command: apt-get update
      - run:
          name: Install dependencies
          command: apt-get install -y libssl-dev libicu-dev
      - run:
          name: Compile code
          command: swift build
      - run:
          name: Run unit tests
          command: swift test
      - store_test_results:
          path: ./

  linux-release:
    docker:
      - image: swift:5.1
    steps:
      - checkout
      - run:
          name: Update package
          command: apt-get update
      - run:
          name: Install dependencies
          command: apt-get install -y libssl-dev libicu-dev
      - run:
          name: Compile code with optimizations
          command: swift build -c release
      - run:
          name: Run unit tests
          command: swift test

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - linux
      - linux-release
      
